root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/server/main.go"
bin = "./tmp/main"
full_bin = "GO_ENV=development ./tmp/main"
include_ext = ["go", "js"]  # Include js to detect when TypeScript compiles
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
include_dir = []
exclude_file = []
delay = 1000
stop_on_error = true
log = "build-errors.log"

[log]
time = true

[misc]
clean_on_exit = true