create table "public"."analysis" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "extracted_events" jsonb,
    "extracted_num_beds" smallint,
    "additional_data" jsonb
);


alter table "public"."analysis" enable row level security;

alter table "public"."calls" add column "fk_analysis" bigint;

CREATE UNIQUE INDEX analysis_pkey ON public.analysis USING btree (id);

alter table "public"."analysis" add constraint "analysis_pkey" PRIMARY KEY using index "analysis_pkey";

alter table "public"."calls" add constraint "calls_fk_analysis_fkey" FOREIGN KEY (fk_analysis) REFERENCES analysis(id) not valid;

alter table "public"."calls" validate constraint "calls_fk_analysis_fkey";

grant delete on table "public"."analysis" to "anon";

grant insert on table "public"."analysis" to "anon";

grant references on table "public"."analysis" to "anon";

grant select on table "public"."analysis" to "anon";

grant trigger on table "public"."analysis" to "anon";

grant truncate on table "public"."analysis" to "anon";

grant update on table "public"."analysis" to "anon";

grant delete on table "public"."analysis" to "authenticated";

grant insert on table "public"."analysis" to "authenticated";

grant references on table "public"."analysis" to "authenticated";

grant select on table "public"."analysis" to "authenticated";

grant trigger on table "public"."analysis" to "authenticated";

grant truncate on table "public"."analysis" to "authenticated";

grant update on table "public"."analysis" to "authenticated";

grant delete on table "public"."analysis" to "service_role";

grant insert on table "public"."analysis" to "service_role";

grant references on table "public"."analysis" to "service_role";

grant select on table "public"."analysis" to "service_role";

grant trigger on table "public"."analysis" to "service_role";

grant truncate on table "public"."analysis" to "service_role";

grant update on table "public"."analysis" to "service_role";


